#!/bin/sh

INFO_DIR="/mnt/SDCARD/RetroArch/.retroarch/cores"
DEFAULT_IMG="/mnt/SDCARD/Themes/SPRUCE/icons/ports.png"

FLAG_FILE="/mnt/SDCARD/.tmp_update/flags/gs.lock"
LIST_FILE="/mnt/SDCARD/.tmp_update/flags/gs_list"
TEMP_FILE="/mnt/SDCARD/.tmp_update/flags/gs_list_temp"
LONG_PRESSED=false

add_game_to_list() {
    # assume game command file exist

    # get game path
    CMD=`cat /tmp/cmd_to_run.sh`

    # update switcher game list
    if [ -f "$LIST_FILE" ] ; then
        # if game list file exists
        # get all commands except the current game
        grep -Fxv "$CMD" "$LIST_FILE" > "$TEMP_FILE"
        mv "$TEMP_FILE" "$LIST_FILE"
        # append the command for current game to the end of game list file 
        echo "$CMD" >> "$LIST_FILE"
    else
        # if game list file does not exist
        # put command to new game list file
        echo "$CMD" > "$LIST_FILE"
    fi
}

prepare_run_switcher() {
    # makesure all emulators and games in list exist
    # remove all non existing games from list file
    rm -f "$TEMP_FILE"
    while read -r CMD; do
        EMU_PATH=`echo $CMD | cut -d\" -f2`
        GAME_PATH=`echo $CMD | cut -d\" -f4`
        if [ ! -f "$EMU_PATH" ] ; then continue ; fi
        if [ ! -f "$GAME_PATH" ] ; then continue ; fi
        echo "$CMD" >> "$TEMP_FILE"
    done <$LIST_FILE
    mv "$TEMP_FILE" "$LIST_FILE"

    # trim the game list to only recent 10 games
    tail -10 "$LIST_FILE" > "$TEMP_FILE"
    mv "$TEMP_FILE" "$LIST_FILE"

    # kill RA or other emulator or MainUI
    killall -q -15 retroarch || killall -q -15 ra32.miyoo || killall -q -9 MainUI || /mnt/SDCARD/miyoo/app/kill_apps.sh

    # set flag file for principal.sh to load game switcher later
    touch "$FLAG_FILE"
}

long_press_handler() {
    # set flag for long pressed event
    LONG_PRESSED=false
    sleep 2
    LONG_PRESSED=true    

    add_game_to_list
    prepare_run_switcher
}

# listen to log file and handle key press events
# the keypress logs are generated by keymon
tail -F -n 1 /var/log/messages | while read line; do
    case $line in
        *"key 1 1 1"*) # MENU key down
            # if in game now
            if [ -f /tmp/cmd_to_run.sh ] ; then

                if pgrep -x "./drastic" > /dev/null ; then
                    long_press_handler &
                    PID=$!
                else
                    add_game_to_list
                    prepare_run_switcher
                fi
            fi
        ;;
        *"key 1 28 1"*) # Start key down
            # if in MainUI menu now and game list exists
            if pgrep -x "./MainUI" > /dev/null && [ -f "$LIST_FILE" ] ; then
                killall -STOP MainUI
                prepare_run_switcher
            fi
        ;;
        *"key 1 1 0"*) # MENU key up
            # kill the long press handler if 
            # menu button is released within time limit
            # and is in game now
            if [ "$LONG_PRESSED" = false ] && [ -f /tmp/cmd_to_run.sh ] ; then
                kill $PID
            fi
        ;;
    esac
done 
